version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker_compose_my_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=myapp
      - DB_USER=postgres
      - DB_PASS=passer
      - DB_URL=jdbc:postgresql://postgres:5432/myapp

  postgres:
    image: postgres:15 #khadimlo1996/postgres:yacine
    restart: always
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passer
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  app-network:
volumes:
  db_data:
